server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/oauthsample.p12
    key-store-password: changeit
    key-alias: oauthsample
    enabled: true
  tomcat:
    use-relative-redirects: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
spring:
  data:
    mongodb:
      uri: mongodb+srv://kokkondaabhilash:kokkondaabhilash@cluster0.zych3mc.mongodb.net/?retryWrites=true&w=majority
      database: AlexaOAuthSample