server:
  port: 443
  ssl:
      key-store: keystore.p12
      key-store-password: springboot
      keyStoreType: PKCS12
      keyAlias: tomcat
  tomcat:
    use-relative-redirects: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
spring:
  data:
    mongodb:
      uri: mongodb+srv://kokkondaabhilash:kokkondaabhilash@cluster0.zych3mc.mongodb.net/?retryWrites=true&w=majority
      database: AlexaOAuthSample